// Generated by CoffeeScript 1.6.3
var Db, Server, app, db, express, mongodb, server;

express = require('express');

mongodb = require('mongodb');

Server = mongodb.Server;

Db = mongodb.Db;

server = new Server('localhost', 27017, {
  auto_reconnect: true
});

db = new Db('fciencias', server);

db.open(function(error, database) {
  if (error) {
    return console.log("Hubo un error");
  } else {
    return console.log("Conectado a la BD");
  }
});

app = express();

app.configure(function() {
  app.use(express.logger());
  app.use(express.bodyParser());
  app.use('/css', express["static"](__dirname + '/css'));
  app.use('/bootstrap', express["static"](__dirname + '/bootstrap'));
  app.use('/js', express["static"](__dirname + '/js'));
  app.use('/lib', express["static"](__dirname + '/lib'));
  app.set('views', __dirname + "/views");
  return app.engine('html', require('ejs').renderFile);
});

app.get('/index', function(request, response) {
  return response.render('inicio.html');
});

app.get('/get/:coleccion', function(request, response) {
  return db.collection(request.params.coleccion, function(error, collection) {
    var elementos, stream;
    stream = collection.find(request.query.query).stream();
    elementos = new Array();
    stream.on('data', function(item) {
      return elementos.push(item);
    });
    return stream.on('end', function() {
      response.writeHead(200, {
        'Content-Type': 'text/json',
        'Access-Control-Allow-Origin': '*'
      });
      response.write('call_' + request.params.coleccion + '(' + JSON.stringify(elementos) + ')');
      return response.end();
    });
  });
});

app.post('/update/:coleccion', function(request, response) {
  return db.collection(request.params.coleccion, function(error, collection) {
    return collection.update(request.body.query, {
      $set: request.body.update
    }, {
      upsert: true
    }, function(error, resultado) {
      response.writeHead(200, {
        'Content-Type': 'text/plain',
        'Access-Control-Allow-Origin': '*'
      });
      return response.end('updated');
    });
  });
});

app.post('/delete/:coleccion/:id', function(request, response) {
  return db.collection(request.params.coleccion, function(error, collection) {
    return collection.remove({
      '_id': new BSON.ObjectID(request.params.id)
    }, function(error, resultado) {
      response.writeHead(200, {
        'Content-Type': 'text/plain',
        'Access-Control-Allow-Origin': '*'
      });
      return response.end('deleted');
    });
  });
});

app.post('/insert/:coleccion', function(request, response) {
  return db.collection(request.params.coleccion, function(error, collection) {
    var object;
    object = request.body;
    return collection.insert(object, {
      safe: true
    }, function(error, resultado) {
      response.writeHead(200, {
        'Content-Type': 'text/plain',
        'Access-Control-Allow-Origin': '*'
      });
      return response.end(object._id.toString());
    });
  });
});

app.listen(8080);
