// Generated by CoffeeScript 1.6.3
var app, express;

express = require('express');

app = express();

app.configure(function() {
  app.use(express.logger());
  app.use(express.bodyParser());
  app.set('views', __dirname + "/views");
  return app.engine('html', require('ejs').renderFile);
});

app.get('/index', function(request, response) {
  return response.render('inicio.html');
});

app.listen(8080);
